-- use ecommerce_db

-- Sales Analysis
-- What is the total revenue generated by the business?
SELECT
    ROUND(SUM(order_value), 2) AS total_revenue
FROM brazilian_ecommerce;

-- How many orders have been placed?
SELECT
    COUNT(DISTINCT order_id) AS total_orders
FROM brazilian_ecommerce;

-- What is the average amount customers spend per order?
SELECT
    ROUND(
        SUM(order_value) / COUNT(DISTINCT order_id),
        2
    ) AS average_order_value
FROM brazilian_ecommerce;

-- How much revenue comes from each order status?
SELECT
    order_status,
    ROUND(SUM(order_value),2) AS revenue,
    COUNT(DISTINCT order_id) AS total_orders
FROM brazilian_ecommerce
GROUP BY order_status
ORDER BY revenue DESC;

-- How has monthly revenue changed over time?
SELECT
    YEAR(order_purchase_timestamp) AS purchase_year,
    MONTH(order_purchase_timestamp) AS purchase_month,
    ROUND(SUM(order_value),2) AS revenue
FROM brazilian_ecommerce
GROUP BY
    YEAR(order_purchase_timestamp),
    MONTH(order_purchase_timestamp)
ORDER BY
    purchase_year,
    purchase_month;
    
-- What is the yearly revenue generated by the business?
SELECT
    YEAR(order_purchase_timestamp) AS purchase_year,
    ROUND(SUM(order_value), 2) AS total_revenue,
    COUNT(DISTINCT order_id) AS total_orders
FROM brazilian_ecommerce
GROUP BY YEAR(order_purchase_timestamp)
ORDER BY purchase_year;

-- What is the quarterly revenue trend?
SELECT
    YEAR(order_purchase_timestamp) AS purchase_year,
    QUARTER(order_purchase_timestamp) AS purchase_quarter,
    ROUND(SUM(order_value), 2) AS total_revenue,
    COUNT(DISTINCT order_id) AS total_orders
FROM brazilian_ecommerce
GROUP BY
    YEAR(order_purchase_timestamp),
    QUARTER(order_purchase_timestamp)
ORDER BY
    purchase_year,
    purchase_quarter;

-- Which are the Top 10 highest revenue months?
SELECT
    YEAR(order_purchase_timestamp) AS purchase_year,
    MONTHNAME(order_purchase_timestamp) AS purchase_month,
    ROUND(SUM(order_value), 2) AS total_revenue
FROM brazilian_ecommerce
GROUP BY
    YEAR(order_purchase_timestamp),
    MONTH(order_purchase_timestamp),
    MONTHNAME(order_purchase_timestamp)
ORDER BY total_revenue DESC
LIMIT 10;

-- Which states generate the highest revenue?
SELECT
    customer_state,
    ROUND(SUM(order_value), 2) AS total_revenue,
    COUNT(DISTINCT order_id) AS total_orders
FROM brazilian_ecommerce
GROUP BY customer_state
ORDER BY total_revenue DESC;

-- What are the Top 10 highest value orders?
SELECT
    order_id,
    customer_unique_id,
    ROUND(order_value, 2) AS order_value,
    order_purchase_timestamp
FROM brazilian_ecommerce
ORDER BY order_value DESC
LIMIT 10;

--  Customer Analysis
-- How many unique customers has the business served?
SELECT
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM brazilian_ecommerce;

-- How many new and returning customers are there?
SELECT
    customer_type,
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM brazilian_ecommerce
GROUP BY customer_type;

-- Which states have the highest number of unique customers?
SELECT
    customer_state,
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM brazilian_ecommerce
GROUP BY customer_state
ORDER BY total_customers DESC;

-- Which cities have the highest number of unique customers?
SELECT
    customer_city,
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM brazilian_ecommerce
GROUP BY customer_city
ORDER BY total_customers DESC
LIMIT 10;

-- What is the average order value by customer type?
SELECT
    customer_type,
    ROUND(
        SUM(order_value) / COUNT(DISTINCT order_id),
        2
    ) AS average_order_value
FROM brazilian_ecommerce
GROUP BY customer_type;

-- Which customer type generates the highest revenue?
SELECT
    customer_type,
    ROUND(SUM(order_value),2) AS total_revenue
FROM brazilian_ecommerce
GROUP BY customer_type
ORDER BY total_revenue DESC;

-- Which states generate the highest average order value?
SELECT
    customer_state,
    ROUND(
        SUM(order_value) / COUNT(DISTINCT order_id),
        2
    ) AS average_order_value
FROM brazilian_ecommerce
GROUP BY customer_state
ORDER BY average_order_value DESC;

-- Which customers placed the highest number of orders?
SELECT
    customer_unique_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM brazilian_ecommerce
GROUP BY customer_unique_id
ORDER BY total_orders DESC
LIMIT 10;

-- Which customers generated the highest revenue?
SELECT
    customer_unique_id,
    ROUND(SUM(order_value),2) AS total_revenue
FROM brazilian_ecommerce
GROUP BY customer_unique_id
ORDER BY total_revenue DESC
LIMIT 10;

-- Which states have the highest average revenue per customer?
SELECT
    customer_state,
    ROUND(
        SUM(order_value) /
        COUNT(DISTINCT customer_unique_id),
        2
    ) AS revenue_per_customer
FROM brazilian_ecommerce
GROUP BY customer_state
ORDER BY revenue_per_customer DESC;


-- Product & Seller Analysis
-- How many unique products are sold?
SELECT
    COUNT(DISTINCT product_id) AS total_products
FROM brazilian_ecommerce;

-- How many unique sellers are registered?
SELECT
    COUNT(DISTINCT seller_id) AS total_sellers
FROM brazilian_ecommerce;

-- Which are the Top 10 best-selling product categories?
SELECT
    product_category_name_english,
    COUNT(*) AS products_sold
FROM brazilian_ecommerce
GROUP BY product_category_name_english
ORDER BY products_sold DESC
LIMIT 10;

-- Which product categories generate the highest revenue?
SELECT
    product_category_name_english,
    ROUND(SUM(order_value),2) AS total_revenue
FROM brazilian_ecommerce
GROUP BY product_category_name_english
ORDER BY total_revenue DESC
LIMIT 10;

-- Which sellers generated the highest revenue?
SELECT
    seller_id,
    ROUND(SUM(order_value),2) AS total_revenue
FROM brazilian_ecommerce
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 10;

-- Which sellers sold the highest number of products?
SELECT
    seller_id,
    COUNT(product_id) AS products_sold
FROM brazilian_ecommerce
GROUP BY seller_id
ORDER BY products_sold DESC
LIMIT 10;

-- What is the average product price by category?
SELECT
    product_category_name_english,
    ROUND(AVG(price),2) AS average_price
FROM brazilian_ecommerce
GROUP BY product_category_name_english
ORDER BY average_price DESC;

-- Which product categories have the highest average freight cost?
SELECT
    product_category_name_english,
    ROUND(AVG(freight_value),2) AS average_freight
FROM brazilian_ecommerce
GROUP BY product_category_name_english
ORDER BY average_freight DESC;

-- Which sellers have served the highest number of unique customers?
SELECT
    seller_id,
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM brazilian_ecommerce
GROUP BY seller_id
ORDER BY total_customers DESC
LIMIT 10;

-- Which product categories contain the highest number of unique products?
SELECT
    product_category_name_english,
    COUNT(DISTINCT product_id) AS unique_products
FROM brazilian_ecommerce
GROUP BY product_category_name_english
ORDER BY unique_products DESC;

-- Delivery Analysis
-- What is the average delivery time?
SELECT
    ROUND(AVG(delivery_days),2) AS average_delivery_days
FROM brazilian_ecommerce;

-- How many orders were delivered on time and delayed?
SELECT
    delivery_status,
    COUNT(DISTINCT order_id) AS total_orders
FROM brazilian_ecommerce
GROUP BY delivery_status;

-- Which states have the highest average delivery time?
SELECT
    customer_state,
    ROUND(AVG(delivery_days),2) AS average_delivery_days
FROM brazilian_ecommerce
GROUP BY customer_state
ORDER BY average_delivery_days DESC;

-- Which states experience the highest average delivery delay?
SELECT
    customer_state,
    ROUND(AVG(delivery_delay),2) AS average_delay
FROM brazilian_ecommerce
GROUP BY customer_state
ORDER BY average_delay DESC;

-- What is the average delivery time by order status?
SELECT
    order_status,
    ROUND(AVG(delivery_days),2) AS average_delivery_days
FROM brazilian_ecommerce
GROUP BY order_status
ORDER BY average_delivery_days;

-- Which months have the highest average delivery time?
SELECT
    YEAR(order_purchase_timestamp) AS purchase_year,
    MONTHNAME(order_purchase_timestamp) AS purchase_month,
    ROUND(AVG(delivery_days),2) AS average_delivery_days
FROM brazilian_ecommerce
GROUP BY
    YEAR(order_purchase_timestamp),
    MONTH(order_purchase_timestamp),
    MONTHNAME(order_purchase_timestamp)
ORDER BY average_delivery_days DESC;

-- How many orders were delivered each year?
SELECT
    YEAR(order_purchase_timestamp) AS purchase_year,
    COUNT(DISTINCT order_id) AS total_orders
FROM brazilian_ecommerce
GROUP BY YEAR(order_purchase_timestamp)
ORDER BY purchase_year;

-- Which sellers have the fastest average delivery time?
SELECT
    seller_id,
    ROUND(AVG(delivery_days),2) AS average_delivery_days
FROM brazilian_ecommerce
GROUP BY seller_id
ORDER BY average_delivery_days
LIMIT 10;

-- Which sellers have the slowest average delivery time?
SELECT
    seller_id,
    ROUND(AVG(delivery_days),2) AS average_delivery_days
FROM brazilian_ecommerce
GROUP BY seller_id
ORDER BY average_delivery_days DESC
LIMIT 10;

-- Which product categories have the highest average delivery time?
SELECT
    product_category_name_english,
    ROUND(AVG(delivery_days),2) AS average_delivery_days
FROM brazilian_ecommerce
GROUP BY product_category_name_english
ORDER BY average_delivery_days DESC;

-- Payment Analysis
-- Which payment methods are most preferred by customers?
SELECT
    payment_type,
    COUNT(*) AS total_transactions
FROM brazilian_ecommerce
GROUP BY payment_type
ORDER BY total_transactions DESC;

-- How many unique orders were paid using each payment method?
SELECT
    payment_type,
    COUNT(DISTINCT order_id) AS total_orders
FROM brazilian_ecommerce
GROUP BY payment_type
ORDER BY total_orders DESC;

-- What is the average payment amount for each payment method?
SELECT
    payment_type,
    ROUND(AVG(payment_value),2) AS average_payment
FROM brazilian_ecommerce
GROUP BY payment_type
ORDER BY average_payment DESC;

-- What is the average number of installments used for each payment method?
SELECT
    payment_type,
    ROUND(AVG(payment_installments),2) AS average_installments
FROM brazilian_ecommerce
GROUP BY payment_type
ORDER BY average_installments DESC;

-- Which payment methods are most commonly used for high-value orders (Order Value > 500)?
SELECT
    payment_type,
    COUNT(DISTINCT order_id) AS total_orders
FROM brazilian_ecommerce
WHERE order_value > 500
GROUP BY payment_type
ORDER BY total_orders DESC;

-- What is the distribution of installment plans?
SELECT
    payment_installments,
    COUNT(*) AS total_transactions
FROM brazilian_ecommerce
GROUP BY payment_installments
ORDER BY payment_installments;

-- What is the average payment amount by customer state?
SELECT
    customer_state,
    ROUND(AVG(payment_value),2) AS average_payment
FROM brazilian_ecommerce
GROUP BY customer_state
ORDER BY average_payment DESC;

-- Which states have the highest average installment count?
SELECT
    customer_state,
    ROUND(AVG(payment_installments),2) AS average_installments
FROM brazilian_ecommerce
GROUP BY customer_state
ORDER BY average_installments DESC;

-- Which customer types use the highest average number of installments?
SELECT
    customer_type,
    ROUND(AVG(payment_installments),2) AS average_installments
FROM brazilian_ecommerce
GROUP BY customer_type
ORDER BY average_installments DESC;

-- What is the average payment amount by year?
SELECT
    YEAR(order_purchase_timestamp) AS purchase_year,
    ROUND(AVG(payment_value),2) AS average_payment
FROM brazilian_ecommerce
GROUP BY YEAR(order_purchase_timestamp)
ORDER BY purchase_year;